-- Compras originam lotes. Estoque e vendas sem origem conhecida continuam sem lote.
create table public.purchase_batches (
  id uuid primary key default gen_random_uuid(),
  batch_number bigint generated by default as identity unique,
  purchase_date date not null default current_date,
  notes text,
  is_legacy boolean not null default false,
  status text not null default 'ABERTO' check (status in ('ABERTO', 'FINALIZADO', 'CANCELADO')),
  created_by uuid references public.profiles (id) on delete set null,
  created_at timestamptz not null default now(),
  closed_at timestamptz,
  cancelled_at timestamptz
);

create table public.batch_items (
  id uuid primary key default gen_random_uuid(),
  batch_id uuid not null references public.purchase_batches (id) on delete restrict,
  product_id uuid not null references public.products (id) on delete restrict,
  variant_id uuid not null references public.product_variants (id) on delete restrict,
  product_name text not null,
  variant_name text not null,
  quantity_purchased integer not null check (quantity_purchased > 0),
  unit_cost numeric(14, 2) not null check (unit_cost >= 0),
  created_at timestamptz not null default now()
);
create index batch_items_batch_idx on public.batch_items (batch_id);
create index batch_items_variant_idx on public.batch_items (variant_id, created_at);

alter table public.stock_movements
  add column batch_id uuid references public.purchase_batches (id) on delete restrict,
  add column batch_item_id uuid references public.batch_items (id) on delete restrict;

insert into public.movement_types (code, name, direction, manual)
values ('ENTRADA_COMPRA', 'Entrada de compra', 1, false)
on conflict (code) do update set name = excluded.name, direction = 1, manual = false;
insert into public.movement_types (code, name, direction, manual) values
  ('ENTRADA_LEGADO', 'Classificação de estoque legado', 1, false),
  ('SAIDA_RECLASSIFICACAO', 'Retirada do saldo sem lote', -1, false)
on conflict (code) do update set name = excluded.name, direction = excluded.direction, manual = false;

create table public.sale_item_batch_allocations (
  id uuid primary key default gen_random_uuid(),
  sale_item_id uuid not null references public.sale_items (id) on delete restrict,
  batch_item_id uuid not null references public.batch_items (id) on delete restrict,
  quantity integer not null check (quantity > 0),
  unit_cost numeric(14, 2) not null check (unit_cost >= 0),
  unit_transfer numeric(14, 2) not null check (unit_transfer >= 0),
  unit_price numeric(14, 2) not null check (unit_price >= unit_transfer),
  created_at timestamptz not null default now(),
  reversed_at timestamptz
);
create index sale_batch_allocations_sale_idx
  on public.sale_item_batch_allocations (sale_item_id, reversed_at);
create index sale_batch_allocations_batch_item_idx
  on public.sale_item_batch_allocations (batch_item_id, reversed_at);

-- Keep old cost snapshots and allow exact line totals when a sale spans lots.
alter table public.sale_items
  alter column line_cost drop expression,
  alter column line_father_profit drop expression;
update public.sale_items
set line_cost = case when cost_price_unit is null then null
                     else (quantity::numeric * cost_price_unit)::numeric(14, 2) end,
    line_father_profit = case when cost_price_unit is null then null
                              else (quantity::numeric * (unit_transfer - cost_price_unit))::numeric(14, 2) end;
alter table public.sale_items drop constraint if exists sale_items_transfer_covers_cost;

create or replace function public.snapshot_sale_item_cost()
returns trigger language plpgsql security definer set search_path = public as $$
declare
  v_cost numeric(14, 2);
  v_override text := current_setting('pods.batch_cost_override', true);
begin
  if nullif(v_override, '') is not null then
    new.cost_price_unit := v_override::numeric(14, 2);
  elsif tg_op = 'INSERT' or new.product_id is distinct from old.product_id then
    select cost_price into v_cost from public.products where id = new.product_id and active;
    if v_cost is null then raise exception 'Custo do estoque sem lote não está configurado para este produto'; end if;
    new.cost_price_unit := v_cost;
  else
    new.cost_price_unit := old.cost_price_unit;
  end if;
  if new.cost_price_unit < 0 then raise exception 'Preço de custo deve ser maior ou igual a zero'; end if;
  if new.unit_price < new.unit_transfer then raise exception 'O preço de venda não pode ser menor que o repasse ao pai'; end if;
  return new;
end;
$$;

create or replace function public.set_sale_item_cost_totals()
returns trigger language plpgsql set search_path = public as $$
begin
  if new.line_cost is null and new.cost_price_unit is not null then
    new.line_cost := (new.quantity::numeric * new.cost_price_unit)::numeric(14, 2);
  end if;
  if new.line_cost is not null then
    new.line_father_profit := (new.quantity::numeric * new.unit_transfer - new.line_cost)::numeric(14, 2);
  else
    new.line_father_profit := null;
  end if;
  return new;
end;
$$;
drop trigger if exists sale_items_cost_totals on public.sale_items;
create trigger sale_items_cost_totals
  before insert or update of quantity, unit_transfer, cost_price_unit, line_cost
  on public.sale_items for each row execute function public.set_sale_item_cost_totals();

create or replace function public.validate_stock_movement_batch_item()
returns trigger language plpgsql set search_path = public as $$
declare v_batch uuid;
begin
  if new.batch_item_id is null then
    if new.batch_id is not null then raise exception 'Movimentação precisa apontar para o item do lote'; end if;
    return new;
  end if;
  select batch_id into v_batch from public.batch_items where id = new.batch_item_id;
  if v_batch is null or new.batch_id is distinct from v_batch then
    raise exception 'Item e lote da movimentação não correspondem';
  end if;
  return new;
end;
$$;

create or replace view public.stock_movement_history
with (security_invoker = true) as
select m.id, m.product_id, m.variant_id, m.movement_type, mt.name as movement_name,
  mt.direction, m.quantity, m.movement_date, m.sale_id, m.notes, m.created_by, m.created_at,
  p.name as product_name, public.flavor_display_name(v.name, v.is_ice) as variant_name,
  pr.full_name as user_name,
  v.is_ice as variant_is_ice, b.batch_number
from public.stock_movements m
join public.movement_types mt on mt.code = m.movement_type
join public.products p on p.id = m.product_id
join public.product_variants v on v.id = m.variant_id
left join public.profiles pr on pr.id = m.created_by
left join public.purchase_batches b on b.id = m.batch_id;
create trigger stock_movement_batch_item_check
  before insert or update of batch_id, batch_item_id on public.stock_movements
  for each row execute function public.validate_stock_movement_batch_item();

create view public.batch_item_balances with (security_invoker = true) as
select bi.id as batch_item_id, bi.batch_id, bi.product_id, bi.variant_id,
  bi.product_name, bi.variant_name, bi.quantity_purchased, bi.unit_cost,
  coalesce(sum(m.quantity * mt.direction), 0)::integer as quantity_remaining
from public.batch_items bi
left join public.stock_movements m on m.batch_item_id = bi.id
left join public.movement_types mt on mt.code = m.movement_type
group by bi.id;

create view public.batch_item_overview with (security_invoker = true) as
select bi.id as batch_item_id, bi.batch_id, b.batch_number, b.purchase_date, b.status, bi.product_id, bi.variant_id,
  bi.product_name, bi.variant_name, bi.quantity_purchased,
  coalesce(sum(a.quantity) filter (where a.reversed_at is null and s.cancelled_at is null), 0)::integer as quantity_sold,
  bal.quantity_remaining, bi.unit_cost,
  (bi.quantity_purchased::numeric * bi.unit_cost)::numeric(14, 2) as investment,
  (bal.quantity_remaining::numeric * bi.unit_cost)::numeric(14, 2) as capital_in_stock
from public.batch_items bi
join public.purchase_batches b on b.id = bi.batch_id
join public.batch_item_balances bal on bal.batch_item_id = bi.id
left join public.sale_item_batch_allocations a on a.batch_item_id = bi.id
left join public.sale_items si on si.id = a.sale_item_id
left join public.sales s on s.id = si.sale_id
group by bi.id, b.batch_number, b.purchase_date, b.status, bal.quantity_remaining;

create view public.batch_overview with (security_invoker = true) as
with item_totals as (
  select b.id as batch_id, b.batch_number, b.purchase_date, b.notes, b.is_legacy, b.status,
    b.created_by, b.created_at, b.closed_at,
    coalesce(sum(bi.quantity_purchased), 0)::integer as total_purchased,
    coalesce(sum(bi.quantity_purchased::numeric * bi.unit_cost), 0)::numeric(14, 2) as capital_invested,
    coalesce(sum(bal.quantity_remaining), 0)::integer as quantity_remaining,
    coalesce(sum(bal.quantity_remaining::numeric * bi.unit_cost), 0)::numeric(14, 2) as capital_in_stock
  from public.purchase_batches b
  left join public.batch_items bi on bi.batch_id = b.id
  left join public.batch_item_balances bal on bal.batch_item_id = bi.id
  group by b.id
), allocations as (
  select bi.batch_id,
    coalesce(sum(a.quantity) filter (where a.reversed_at is null and s.cancelled_at is null), 0)::integer as quantity_sold,
    coalesce(sum(a.quantity::numeric * a.unit_cost) filter (where a.reversed_at is null and s.cancelled_at is null), 0)::numeric(14, 2) as capital_recovered,
    coalesce(sum(a.quantity::numeric * a.unit_price) filter (where a.reversed_at is null and s.cancelled_at is null), 0)::numeric(14, 2) as revenue,
    coalesce(sum(a.quantity::numeric * a.unit_price) filter (where a.reversed_at is null and s.cancelled_at is null and so.counts_as_received), 0)::numeric(14, 2) as revenue_received,
    coalesce(sum(a.quantity::numeric * a.unit_price) filter (where a.reversed_at is null and s.cancelled_at is null and so.counts_as_receivable), 0)::numeric(14, 2) as revenue_receivable,
    coalesce(sum(a.quantity::numeric * a.unit_transfer) filter (where a.reversed_at is null and s.cancelled_at is null), 0)::numeric(14, 2) as transfer_total,
    coalesce(sum(a.quantity::numeric * a.unit_transfer) filter (where a.reversed_at is null and s.cancelled_at is null and s.transfer_paid), 0)::numeric(14, 2) as transfer_paid,
    coalesce(sum(a.quantity::numeric * a.unit_transfer) filter (where a.reversed_at is null and s.cancelled_at is null and so.transfer_due_now), 0)::numeric(14, 2) as transfer_due_now,
    coalesce(sum(a.quantity::numeric * a.unit_transfer) filter (where a.reversed_at is null and s.cancelled_at is null and so.transfer_is_future), 0)::numeric(14, 2) as transfer_future,
    coalesce(sum(a.quantity::numeric * (a.unit_transfer - a.unit_cost)) filter (where a.reversed_at is null and s.cancelled_at is null), 0)::numeric(14, 2) as father_profit,
    coalesce(sum(a.quantity::numeric * (a.unit_price - a.unit_transfer)) filter (where a.reversed_at is null and s.cancelled_at is null), 0)::numeric(14, 2) as child_profit,
    coalesce(sum(a.quantity::numeric * (a.unit_price - a.unit_cost)) filter (where a.reversed_at is null and s.cancelled_at is null), 0)::numeric(14, 2) as total_profit,
    max(s.sale_date) filter (where a.reversed_at is null and s.cancelled_at is null) as last_sale_date,
    count(*) > 0 as has_sales
  from public.sale_item_batch_allocations a
  join public.batch_items bi on bi.id = a.batch_item_id
  join public.sale_items si on si.id = a.sale_item_id
  join public.sales s on s.id = si.sale_id
  join public.sales_overview so on so.id = s.id
  group by bi.batch_id
)
select i.*,
  coalesce(a.quantity_sold, 0)::integer as quantity_sold,
  coalesce(a.capital_recovered, 0)::numeric(14, 2) as capital_recovered,
  coalesce(a.revenue, 0)::numeric(14, 2) as revenue,
  coalesce(a.revenue_received, 0)::numeric(14, 2) as revenue_received,
  coalesce(a.revenue_receivable, 0)::numeric(14, 2) as revenue_receivable,
  coalesce(a.transfer_total, 0)::numeric(14, 2) as transfer_total,
  coalesce(a.transfer_paid, 0)::numeric(14, 2) as transfer_paid,
  coalesce(a.transfer_due_now, 0)::numeric(14, 2) as transfer_due_now,
  coalesce(a.transfer_future, 0)::numeric(14, 2) as transfer_future,
  coalesce(a.father_profit, 0)::numeric(14, 2) as father_profit,
  case when public.has_write_access() then coalesce(a.child_profit, 0)::numeric(14, 2) else null::numeric end as child_profit,
  case when public.has_write_access() then coalesce(a.total_profit, 0)::numeric(14, 2) else null::numeric end as total_profit,
  a.last_sale_date,
  coalesce(a.has_sales, false) as has_sales,
  case when i.status = 'FINALIZADO' and a.quantity_sold = i.total_purchased and a.last_sale_date is not null
    then a.last_sale_date - i.purchase_date else null end as duration_days
from item_totals i left join allocations a on a.batch_id = i.batch_id;

create or replace function public.refresh_batch_status_from_movement()
returns trigger language plpgsql security definer set search_path = public as $$
declare
  v_batch uuid;
  v_remaining integer;
begin
  if tg_op = 'DELETE' then v_batch := old.batch_id; else v_batch := new.batch_id; end if;
  if v_batch is null then return null; end if;
  select coalesce(sum(bal.quantity_remaining), 0)::integer into v_remaining
  from public.batch_item_balances bal where bal.batch_id = v_batch;
  update public.purchase_batches
  set status = case when v_remaining = 0 then 'FINALIZADO' else 'ABERTO' end,
      closed_at = case when v_remaining = 0 then coalesce(closed_at, now()) else null end
  where id = v_batch and status <> 'CANCELADO';
  return null;
end;
$$;
create trigger stock_movement_refresh_batch_status
  after insert or update or delete on public.stock_movements
  for each row execute function public.refresh_batch_status_from_movement();

create or replace function public.allocate_sale_item_fifo(
  p_sale_item_id uuid, p_product_id uuid, p_variant_id uuid, p_quantity integer,
  p_sale_date date, p_unit_price numeric(14, 2), p_unit_transfer numeric(14, 2), p_user uuid
)
returns void language plpgsql security definer set search_path = public as $$
declare
  v_available integer;
  v_batch_total integer;
  v_legacy integer;
  v_left integer := p_quantity;
  v_take integer;
  v_product_cost numeric(14, 2);
  v_cost_total numeric(14, 2) := 0;
  v_avg_cost numeric(14, 2);
  v_batch record;
  v_sale_id uuid;
begin
  if p_quantity <= 0 then raise exception 'Quantidade inválida'; end if;
  perform 1 from public.product_variants where id = p_variant_id for update;
  select coalesce(sum(m.quantity * mt.direction), 0)::integer into v_available
  from public.stock_movements m join public.movement_types mt on mt.code = m.movement_type
  where m.variant_id = p_variant_id;
  if coalesce(v_available, 0) < p_quantity then
    raise exception 'Estoque insuficiente. Disponível: %', coalesce(v_available, 0);
  end if;
  select coalesce(sum(quantity_remaining), 0)::integer into v_batch_total
  from public.batch_item_balances where variant_id = p_variant_id;
  v_legacy := greatest(v_available - v_batch_total, 0);
  select sale_id into v_sale_id from public.sale_items where id = p_sale_item_id;

  -- Unidades antigas ou de ajuste sem origem permanecem explicitamente sem lote.
  if v_legacy > 0 then
    select cost_price into v_product_cost from public.products where id = p_product_id;
    if v_product_cost is null then raise exception 'O estoque sem lote deste produto não possui custo configurado'; end if;
    if v_product_cost > p_unit_transfer then raise exception 'O custo atual supera o repasse desta venda'; end if;
    v_take := least(v_left, v_legacy);
    insert into public.stock_movements (product_id, variant_id, movement_type, quantity, movement_date, sale_id, notes, created_by)
    values (p_product_id, p_variant_id, 'VENDA', v_take, p_sale_date, v_sale_id, 'Baixa de estoque sem lote conhecido', p_user);
    v_cost_total := v_cost_total + v_take::numeric * v_product_cost;
    v_left := v_left - v_take;
  end if;

  for v_batch in
    select bal.batch_item_id, bal.batch_id, bal.quantity_remaining, bi.unit_cost, b.batch_number
    from public.batch_item_balances bal
    join public.batch_items bi on bi.id = bal.batch_item_id
    join public.purchase_batches b on b.id = bal.batch_id
    where bal.variant_id = p_variant_id and bal.quantity_remaining > 0 and b.status <> 'CANCELADO'
    order by b.is_legacy desc, b.purchase_date, b.batch_number, bi.created_at, bi.id
  loop
    exit when v_left = 0;
    v_take := least(v_left, v_batch.quantity_remaining);
    if v_batch.unit_cost > p_unit_transfer then
      raise exception 'O custo do Lote % supera o repasse desta venda', lpad(v_batch.batch_number::text, greatest(3, length(v_batch.batch_number::text)), '0');
    end if;
    insert into public.sale_item_batch_allocations (sale_item_id, batch_item_id, quantity, unit_cost, unit_transfer, unit_price)
    values (p_sale_item_id, v_batch.batch_item_id, v_take, v_batch.unit_cost, p_unit_transfer, p_unit_price);
    insert into public.stock_movements (product_id, variant_id, movement_type, quantity, movement_date, sale_id, notes, created_by, batch_id, batch_item_id)
    values (p_product_id, p_variant_id, 'VENDA', v_take, p_sale_date, v_sale_id,
      'Baixa automática da venda · lote ' || lpad(v_batch.batch_number::text, greatest(3, length(v_batch.batch_number::text)), '0'),
      p_user, v_batch.batch_id, v_batch.batch_item_id);
    v_cost_total := v_cost_total + v_take::numeric * v_batch.unit_cost;
    v_left := v_left - v_take;
  end loop;

  if v_left > 0 then raise exception 'Não foi possível associar todas as unidades ao estoque disponível'; end if;
  v_avg_cost := round(v_cost_total / p_quantity, 2);
  perform set_config('pods.batch_cost_override', v_avg_cost::text, true);
  update public.sale_items set cost_price_unit = v_avg_cost, line_cost = v_cost_total::numeric(14, 2),
    line_father_profit = (p_quantity::numeric * p_unit_transfer - v_cost_total)::numeric(14, 2)
  where id = p_sale_item_id;
  perform set_config('pods.batch_cost_override', '', true);
end;
$$;

create or replace function public.create_purchase(payload jsonb)
returns uuid language plpgsql security definer set search_path = public as $$
declare
  v_user uuid := auth.uid();
  v_batch uuid;
  v_item jsonb;
  v_variant uuid;
  v_product uuid;
  v_product_name text;
  v_variant_name text;
  v_quantity integer;
  v_cost numeric(14, 2);
  v_item_id uuid;
  v_batch_number bigint;
begin
  if v_user is null or not public.has_write_access() then raise exception 'Sem permissão para registrar compra'; end if;
  if jsonb_typeof(payload -> 'items') <> 'array' or jsonb_array_length(payload -> 'items') = 0 then
    raise exception 'Adicione ao menos um produto à compra';
  end if;
  perform 1 from public.product_variants v
  where v.id in (select nullif(value ->> 'variant_id', '')::uuid from jsonb_array_elements(payload -> 'items'))
  order by v.id for update;

  insert into public.purchase_batches (purchase_date, notes, created_by)
  values (coalesce(nullif(payload ->> 'purchase_date', '')::date, current_date),
    nullif(trim(coalesce(payload ->> 'notes', '')), ''), v_user)
  returning id, batch_number into v_batch, v_batch_number;

  for v_item in select value from jsonb_array_elements(payload -> 'items') loop
    v_variant := nullif(v_item ->> 'variant_id', '')::uuid;
    v_quantity := nullif(v_item ->> 'quantity', '')::integer;
    v_cost := nullif(v_item ->> 'unit_cost', '')::numeric(14, 2);
    if v_quantity is null or v_quantity <= 0 or v_cost is null or v_cost < 0 then
      raise exception 'Informe quantidade e custo unitário válidos para todos os itens';
    end if;
    select v.product_id, p.name, v.name into v_product, v_product_name, v_variant_name
    from public.product_variants v join public.products p on p.id = v.product_id
    where v.id = v_variant and v.active and p.active;
    if v_product is null then raise exception 'Produto ou sabor inválido na compra'; end if;
    insert into public.batch_items (batch_id, product_id, variant_id, product_name, variant_name, quantity_purchased, unit_cost)
    values (v_batch, v_product, v_variant, v_product_name, v_variant_name, v_quantity, v_cost)
    returning id into v_item_id;
    insert into public.stock_movements (product_id, variant_id, movement_type, quantity, movement_date, notes, created_by, batch_id, batch_item_id)
    values (v_product, v_variant, 'ENTRADA_COMPRA', v_quantity,
      coalesce(nullif(payload ->> 'purchase_date', '')::date, current_date),
      'Entrada da compra · lote ' || lpad(v_batch_number::text, greatest(3, length(v_batch_number::text)), '0'), v_user, v_batch, v_item_id);
  end loop;
  perform public.write_audit(v_user, 'purchase.created', 'purchase_batches', v_batch, payload);
  return v_batch;
end;
$$;

create or replace function public.create_sale(payload jsonb)
returns uuid language plpgsql security definer set search_path = public as $$
declare
  v_user uuid := auth.uid();
  v_sale_id uuid := gen_random_uuid();
  v_item jsonb;
  v_sale_item_id uuid;
  v_customer_type_id uuid;
  v_payment_status_id uuid;
  v_counts_as_received boolean;
  v_is_credit boolean;
  v_customer_id uuid;
  v_customer_name text;
  v_sale_date date;
  v_notes text;
  v_type_name text;
  v_variant_id uuid;
  v_qty integer;
  v_product_id uuid;
  v_product_name text;
  v_variant_name text;
  v_price numeric(14, 2);
  v_transfer numeric(14, 2);
  v_rule_id uuid;
begin
  if v_user is null then raise exception 'Não autenticado'; end if;
  if not public.has_write_access() then raise exception 'Sem permissão para registrar vendas'; end if;
  v_sale_date := coalesce(nullif(payload ->> 'sale_date', '')::date, current_date);
  v_customer_type_id := nullif(payload ->> 'customer_type_id', '')::uuid;
  v_payment_status_id := nullif(payload ->> 'payment_status_id', '')::uuid;
  v_is_credit := coalesce((payload ->> 'is_credit')::boolean, false);
  v_customer_id := nullif(payload ->> 'customer_id', '')::uuid;
  v_customer_name := nullif(trim(coalesce(payload ->> 'customer_name', '')), '');
  v_notes := nullif(payload ->> 'notes', '');
  if v_customer_name is null and v_customer_id is not null then
    select name into v_customer_name from public.customers where id = v_customer_id;
  end if;
  if v_customer_name is null then raise exception 'Informe o nome do cliente'; end if;
  select counts_as_received into v_counts_as_received from public.payment_statuses
  where id = v_payment_status_id and active and not is_terminal;
  if v_counts_as_received is null then raise exception 'Status de pagamento inválido'; end if;
  if v_counts_as_received then v_is_credit := false; end if;
  select name into v_type_name from public.customer_types where id = v_customer_type_id and active;
  if v_type_name is null then raise exception 'Tipo de cliente inválido'; end if;
  if jsonb_typeof(payload -> 'items') <> 'array' or jsonb_array_length(payload -> 'items') = 0 then
    raise exception 'Informe ao menos um item';
  end if;
  insert into public.sales (id, sale_date, customer_id, customer_name, customer_type_id, customer_type_name,
    payment_status_id, is_credit, notes, created_by)
  values (v_sale_id, v_sale_date, v_customer_id, v_customer_name, v_customer_type_id, v_type_name,
    v_payment_status_id, v_is_credit, v_notes, v_user);

  for v_item in select value from jsonb_array_elements(payload -> 'items') loop
    v_variant_id := nullif(v_item ->> 'variant_id', '')::uuid;
    v_qty := nullif(v_item ->> 'quantity', '')::integer;
    if v_qty is null or v_qty <= 0 then raise exception 'Quantidade inválida'; end if;
    select v.product_id, v.name, p.name into v_product_id, v_variant_name, v_product_name
    from public.product_variants v join public.products p on p.id = v.product_id
    where v.id = v_variant_id and v.active and p.active;
    if v_product_id is null then raise exception 'Produto ou sabor inválido'; end if;
    select id, sale_price, father_transfer into v_rule_id, v_price, v_transfer
    from public.price_rules where product_id = v_product_id and customer_type_id = v_customer_type_id and active;
    if v_price is null then raise exception 'Não há preço configurado para este produto e tipo de cliente'; end if;
    perform set_config('pods.batch_cost_override', '0', true);
    insert into public.sale_items (sale_id, product_id, product_name, variant_id, variant_name, price_rule_id,
      quantity, unit_price, unit_transfer, cost_price_unit, line_cost, line_father_profit)
    values (v_sale_id, v_product_id, v_product_name, v_variant_id, v_variant_name, v_rule_id,
      v_qty, v_price, v_transfer, 0, 0, 0)
    returning id into v_sale_item_id;
    perform set_config('pods.batch_cost_override', '', true);
    perform public.allocate_sale_item_fifo(v_sale_item_id, v_product_id, v_variant_id, v_qty,
      v_sale_date, v_price, v_transfer, v_user);
  end loop;
  perform public.write_audit(v_user, 'sale.created', 'sales', v_sale_id, payload);
  return v_sale_id;
end;
$$;

create or replace function public.update_sale(p_sale_id uuid, payload jsonb)
returns void language plpgsql security definer set search_path = public as $$
declare
  v_user uuid := auth.uid();
  v_sale public.sales%rowtype;
  v_existing public.sale_items%rowtype;
  v_type uuid;
  v_type_name text;
  v_status uuid;
  v_status_received boolean;
  v_is_credit boolean;
  v_customer_id uuid;
  v_customer_name text;
  v_notes text;
  v_sale_date date;
  v_new_variant uuid;
  v_new_qty integer;
  v_product_id uuid;
  v_product_name text;
  v_variant_name text;
  v_price numeric(14, 2);
  v_transfer numeric(14, 2);
  v_rule_id uuid;
  v_changed boolean;
  v_alloc record;
  v_allocated integer;
  v_untracked integer;
begin
  if v_user is null or not public.has_write_access() then raise exception 'Sem permissão para editar vendas'; end if;
  select * into v_sale from public.sales where id = p_sale_id for update;
  if not found then raise exception 'Venda não encontrada'; end if;
  if v_sale.cancelled_at is not null then raise exception 'Venda cancelada não pode ser editada'; end if;
  if (select count(*) from public.sale_items where sale_id = p_sale_id) <> 1 then
    raise exception 'Edição disponível para vendas com um item';
  end if;
  select * into v_existing from public.sale_items where sale_id = p_sale_id limit 1;
  v_type := coalesce(nullif(payload ->> 'customer_type_id', '')::uuid, v_sale.customer_type_id);
  v_status := coalesce(nullif(payload ->> 'payment_status_id', '')::uuid, v_sale.payment_status_id);
  v_customer_id := case when payload ? 'customer_id' then nullif(payload ->> 'customer_id', '')::uuid else v_sale.customer_id end;
  v_customer_name := coalesce(nullif(trim(coalesce(payload ->> 'customer_name', '')), ''), v_sale.customer_name);
  v_notes := case when payload ? 'notes' then nullif(payload ->> 'notes', '') else v_sale.notes end;
  v_sale_date := coalesce(nullif(payload ->> 'sale_date', '')::date, v_sale.sale_date);
  v_new_variant := coalesce(nullif(payload ->> 'variant_id', '')::uuid, v_existing.variant_id);
  v_new_qty := coalesce(nullif(payload ->> 'quantity', '')::integer, v_existing.quantity);
  if v_new_qty is null or v_new_qty <= 0 then raise exception 'Quantidade inválida'; end if;
  select name into v_type_name from public.customer_types where id = v_type and active;
  if v_type_name is null then raise exception 'Tipo de cliente inválido'; end if;
  select counts_as_received into v_status_received from public.payment_statuses
  where id = v_status and active and not is_terminal;
  if v_status_received is null then raise exception 'Status de pagamento inválido'; end if;
  if v_status_received then v_is_credit := v_sale.is_credit;
  else v_is_credit := coalesce((payload ->> 'is_credit')::boolean, v_sale.is_credit); end if;
  v_changed := v_new_variant is distinct from v_existing.variant_id
    or v_new_qty is distinct from v_existing.quantity or v_type is distinct from v_sale.customer_type_id;
  if v_sale.transfer_paid and (v_changed or v_is_credit is distinct from v_sale.is_credit) then
    raise exception 'O repasse desta venda já foi pago. Não é possível alterar produto, quantidade, tipo ou fiado.';
  end if;

  if v_changed then
    select coalesce(sum(a.quantity), 0)::integer into v_allocated
    from public.sale_item_batch_allocations a where a.sale_item_id = v_existing.id and a.reversed_at is null;
    for v_alloc in
      select a.*, bi.product_id, bi.variant_id, bi.batch_id
      from public.sale_item_batch_allocations a join public.batch_items bi on bi.id = a.batch_item_id
      where a.sale_item_id = v_existing.id and a.reversed_at is null
    loop
      insert into public.stock_movements (product_id, variant_id, movement_type, quantity, movement_date, sale_id,
        notes, created_by, batch_id, batch_item_id)
      values (v_alloc.product_id, v_alloc.variant_id, 'ESTORNO_EDICAO', v_alloc.quantity, current_date,
        p_sale_id, 'Devolução ao lote por edição da venda', v_user, v_alloc.batch_id, v_alloc.batch_item_id);
      update public.sale_item_batch_allocations set reversed_at = now() where id = v_alloc.id;
    end loop;
    v_untracked := v_existing.quantity - coalesce(v_allocated, 0);
    if v_untracked > 0 then
      insert into public.stock_movements (product_id, variant_id, movement_type, quantity, movement_date, sale_id, notes, created_by)
      values (v_existing.product_id, v_existing.variant_id, 'ESTORNO_EDICAO', v_untracked, current_date,
        p_sale_id, 'Devolução de estoque sem lote por edição da venda', v_user);
    end if;

    select v.product_id, v.name, p.name into v_product_id, v_variant_name, v_product_name
    from public.product_variants v join public.products p on p.id = v.product_id
    where v.id = v_new_variant and v.active and p.active;
    if v_product_id is null then raise exception 'Produto ou sabor inválido'; end if;
    if v_new_variant = v_existing.variant_id and v_type = v_sale.customer_type_id then
      v_price := v_existing.unit_price; v_transfer := v_existing.unit_transfer; v_rule_id := v_existing.price_rule_id;
    else
      select id, sale_price, father_transfer into v_rule_id, v_price, v_transfer
      from public.price_rules where product_id = v_product_id and customer_type_id = v_type and active;
      if v_price is null then raise exception 'Não há preço configurado para este produto e tipo de cliente'; end if;
    end if;
    perform set_config('pods.batch_cost_override', '0', true);
    update public.sale_items set product_id = v_product_id, product_name = v_product_name,
      variant_id = v_new_variant, variant_name = v_variant_name, price_rule_id = v_rule_id,
      quantity = v_new_qty, unit_price = v_price, unit_transfer = v_transfer,
      cost_price_unit = 0, line_cost = 0, line_father_profit = 0
    where id = v_existing.id;
    perform set_config('pods.batch_cost_override', '', true);
    perform public.allocate_sale_item_fifo(v_existing.id, v_product_id, v_new_variant, v_new_qty,
      v_sale_date, v_price, v_transfer, v_user);
  end if;

  update public.sales set sale_date = v_sale_date, customer_id = v_customer_id,
    customer_name = v_customer_name, customer_type_id = v_type, customer_type_name = v_type_name,
    payment_status_id = v_status, is_credit = v_is_credit, notes = v_notes where id = p_sale_id;
  update public.stock_movements set movement_date = v_sale_date
  where sale_id = p_sale_id and movement_type = 'VENDA';
  perform public.write_audit(v_user, 'sale.updated', 'sales', p_sale_id, payload);
end;
$$;

create or replace function public.cancel_sale(p_sale_id uuid, p_reason text)
returns void language plpgsql security definer set search_path = public as $$
declare
  v_user uuid := auth.uid();
  v_sale public.sales%rowtype;
  v_item public.sale_items%rowtype;
  v_alloc record;
  v_allocated integer;
  v_untracked integer;
begin
  if v_user is null or not public.has_write_access() then raise exception 'Sem permissão para cancelar vendas'; end if;
  select * into v_sale from public.sales where id = p_sale_id for update;
  if not found then raise exception 'Venda não encontrada'; end if;
  if v_sale.cancelled_at is not null then raise exception 'Venda já cancelada'; end if;
  for v_item in select * from public.sale_items where sale_id = p_sale_id loop
    select coalesce(sum(a.quantity), 0)::integer into v_allocated
    from public.sale_item_batch_allocations a where a.sale_item_id = v_item.id and a.reversed_at is null;
    for v_alloc in
      select a.*, bi.product_id, bi.variant_id, bi.batch_id
      from public.sale_item_batch_allocations a join public.batch_items bi on bi.id = a.batch_item_id
      where a.sale_item_id = v_item.id and a.reversed_at is null
    loop
      insert into public.stock_movements (product_id, variant_id, movement_type, quantity, movement_date, sale_id,
        notes, created_by, batch_id, batch_item_id)
      values (v_alloc.product_id, v_alloc.variant_id, 'CANCELAMENTO_VENDA', v_alloc.quantity, current_date,
        p_sale_id, 'Devolução ao lote por cancelamento', v_user, v_alloc.batch_id, v_alloc.batch_item_id);
      update public.sale_item_batch_allocations set reversed_at = now() where id = v_alloc.id;
    end loop;
    v_untracked := v_item.quantity - coalesce(v_allocated, 0);
    if v_untracked > 0 then
      perform public.write_stock_movement(v_item.product_id, v_item.variant_id, 'CANCELAMENTO_VENDA',
        v_untracked, current_date, p_sale_id, 'Devolução de estoque sem lote por cancelamento', v_user);
    end if;
  end loop;
  update public.sales set cancelled_at = now(), cancelled_by = v_user,
    cancel_reason = nullif(trim(coalesce(p_reason, '')), '') where id = p_sale_id;
  perform public.write_audit(v_user, 'sale.cancelled', 'sales', p_sale_id, jsonb_build_object('reason', p_reason));
end;
$$;

create or replace function public.register_stock_movement(
  p_variant_id uuid, p_type text, p_quantity integer, p_date date, p_notes text
)
returns uuid language plpgsql security definer set search_path = public as $$
declare
  v_user uuid := auth.uid();
  v_product uuid;
  v_manual boolean;
  v_id uuid;
  v_left integer := p_quantity;
  v_take integer;
  v_item record;
  v_available integer;
  v_batch_total integer;
  v_legacy integer;
begin
  if v_user is null or not public.has_write_access() then raise exception 'Sem permissão para movimentar estoque'; end if;
  if p_type = 'ENTRADA' then
    raise exception 'Registre compras em Estoque > Nova compra para criar o lote e guardar o custo histórico';
  end if;
  select manual into v_manual from public.movement_types where code = p_type;
  if v_manual is distinct from true or p_type not in ('AJUSTE_ENTRADA', 'AJUSTE_SAIDA') then
    raise exception 'Use compra para novas mercadorias e ajuste para corrigir divergências';
  end if;
  if p_quantity is null or p_quantity <= 0 then raise exception 'Quantidade inválida'; end if;
  select product_id into v_product from public.product_variants where id = p_variant_id and active;
  if v_product is null then raise exception 'Sabor inválido'; end if;
  perform 1 from public.product_variants where id = p_variant_id for update;

  if p_type = 'AJUSTE_SAIDA' then
    select coalesce(sum(m.quantity * mt.direction), 0)::integer into v_available
    from public.stock_movements m join public.movement_types mt on mt.code = m.movement_type where m.variant_id = p_variant_id;
    select coalesce(sum(quantity_remaining), 0)::integer into v_batch_total
    from public.batch_item_balances where variant_id = p_variant_id;
    v_legacy := greatest(v_available - v_batch_total, 0);
    v_take := least(v_left, v_legacy);
    if v_take > 0 then
      v_id := public.write_stock_movement(v_product, p_variant_id, p_type, v_take, p_date, null,
        nullif(trim(coalesce(p_notes, '')), ''), v_user);
      v_left := v_left - v_take;
    end if;
    for v_item in
      select bal.batch_item_id, bal.batch_id, bal.quantity_remaining
      from public.batch_item_balances bal join public.batch_items bi on bi.id = bal.batch_item_id
      join public.purchase_batches b on b.id = bal.batch_id
      where bal.variant_id = p_variant_id and bal.quantity_remaining > 0 and b.status <> 'CANCELADO'
      order by b.purchase_date desc, b.batch_number desc, bi.created_at desc, bi.id desc
    loop
      exit when v_left = 0;
      v_take := least(v_left, v_item.quantity_remaining);
      insert into public.stock_movements (product_id, variant_id, movement_type, quantity, movement_date, notes,
        created_by, batch_id, batch_item_id)
      values (v_product, p_variant_id, p_type, v_take, coalesce(p_date, current_date),
        nullif(trim(coalesce(p_notes, '')), ''), v_user, v_item.batch_id, v_item.batch_item_id)
      returning id into v_id;
      v_left := v_left - v_take;
    end loop;
  end if;
  if v_left > 0 then
    v_id := public.write_stock_movement(v_product, p_variant_id, p_type, v_left, p_date, null,
      nullif(trim(coalesce(p_notes, '')), ''), v_user);
  end if;
  perform public.write_audit(v_user, 'stock.movement', 'stock_movements', v_id,
    jsonb_build_object('variant_id', p_variant_id, 'type', p_type, 'quantity', p_quantity, 'notes', p_notes));
  return v_id;
end;
$$;

create or replace function public.create_legacy_batch(payload jsonb)
returns uuid language plpgsql security definer set search_path = public as $$
declare
  v_user uuid := auth.uid();
  v_role text;
  v_batch uuid;
  v_item jsonb;
  v_variant uuid;
  v_product uuid;
  v_product_name text;
  v_variant_name text;
  v_quantity integer;
  v_cost numeric(14, 2);
  v_unassigned integer;
  v_batch_stock integer;
  v_system_stock integer;
  v_item_id uuid;
  v_batch_number bigint;
begin
  if v_user is null or not public.has_write_access() then raise exception 'Sem permissão para associar estoque legado'; end if;
  select lower(role_code) into v_role from public.profiles where id = v_user;
  if v_role <> 'admin' then raise exception 'Somente ADMIN pode associar estoque legado'; end if;
  if jsonb_typeof(payload -> 'items') <> 'array' or jsonb_array_length(payload -> 'items') = 0 then
    raise exception 'Adicione ao menos um item sem lote';
  end if;
  perform 1 from public.product_variants v
  where v.id in (select nullif(value ->> 'variant_id', '')::uuid from jsonb_array_elements(payload -> 'items'))
  order by v.id for update;

  insert into public.purchase_batches (purchase_date, notes, is_legacy, created_by)
  values (current_date, coalesce(nullif(trim(coalesce(payload ->> 'notes', '')), ''), 'Associação controlada de estoque legado'),
    true, v_user)
  returning id, batch_number into v_batch, v_batch_number;

  for v_item in select value from jsonb_array_elements(payload -> 'items') loop
    v_variant := nullif(v_item ->> 'variant_id', '')::uuid;
    v_quantity := nullif(v_item ->> 'quantity', '')::integer;
    v_cost := nullif(v_item ->> 'unit_cost', '')::numeric(14, 2);
    if v_quantity is null or v_quantity <= 0 or v_cost is null or v_cost < 0 then
      raise exception 'Informe quantidade e custo unitário histórico conhecido para todos os itens';
    end if;
    select v.product_id, p.name, v.name into v_product, v_product_name, v_variant_name
    from public.product_variants v join public.products p on p.id = v.product_id
    where v.id = v_variant and v.active and p.active;
    if v_product is null then raise exception 'Produto ou sabor inválido'; end if;

    select coalesce(sum(m.quantity * mt.direction), 0)::integer into v_system_stock
    from public.stock_movements m join public.movement_types mt on mt.code = m.movement_type
    where m.variant_id = v_variant;
    select coalesce(sum(quantity_remaining), 0)::integer into v_batch_stock
    from public.batch_item_balances where variant_id = v_variant;
    v_unassigned := greatest(v_system_stock - v_batch_stock, 0);
    if v_unassigned < v_quantity then
      raise exception 'Estoque sem lote insuficiente para %. Disponível: %', v_variant_name, v_unassigned;
    end if;

    insert into public.batch_items (batch_id, product_id, variant_id, product_name, variant_name, quantity_purchased, unit_cost)
    values (v_batch, v_product, v_variant, v_product_name, v_variant_name, v_quantity, v_cost)
    returning id into v_item_id;
    insert into public.stock_movements (product_id, variant_id, movement_type, quantity, movement_date, notes,
      created_by, batch_id, batch_item_id)
    values (v_product, v_variant, 'ENTRADA_LEGADO', v_quantity, current_date,
      'Associação do saldo existente · Lote ' || lpad(v_batch_number::text, greatest(3, length(v_batch_number::text)), '0'),
      v_user, v_batch, v_item_id);
    insert into public.stock_movements (product_id, variant_id, movement_type, quantity, movement_date, notes, created_by)
    values (v_product, v_variant, 'SAIDA_RECLASSIFICACAO', v_quantity, current_date,
      'Retirada correspondente do saldo sem lote', v_user);
  end loop;

  perform public.write_audit(v_user, 'stock.legacy_associated', 'purchase_batches', v_batch, payload);
  return v_batch;
end;
$$;

revoke all on function public.create_legacy_batch(jsonb) from public;
grant execute on function public.create_legacy_batch(jsonb) to authenticated;

create or replace function public.cancel_purchase_batch(p_batch_id uuid)
returns void language plpgsql security definer set search_path = public as $$
declare
  v_user uuid := auth.uid();
  v_batch public.purchase_batches%rowtype;
  v_item record;
begin
  if v_user is null or not public.has_write_access() then raise exception 'Sem permissão para cancelar compras'; end if;
  select * into v_batch from public.purchase_batches where id = p_batch_id for update;
  if not found then raise exception 'Lote não encontrado'; end if;
  if v_batch.status = 'CANCELADO' then raise exception 'Lote já cancelado'; end if;
  if exists (
    select 1 from public.sale_item_batch_allocations a join public.batch_items bi on bi.id = a.batch_item_id
    where bi.batch_id = p_batch_id
  ) then raise exception 'Este lote já participou de uma venda e não pode ser cancelado'; end if;
  for v_item in select * from public.batch_item_balances where batch_id = p_batch_id loop
    if v_item.quantity_remaining <> v_item.quantity_purchased then
      raise exception 'O estoque do lote mudou; confira e corrija antes de cancelar a compra';
    end if;
    insert into public.stock_movements (product_id, variant_id, movement_type, quantity, movement_date, notes,
      created_by, batch_id, batch_item_id)
    values (v_item.product_id, v_item.variant_id, 'AJUSTE_SAIDA', v_item.quantity_purchased,
      current_date, 'Cancelamento seguro da compra', v_user, p_batch_id, v_item.batch_item_id);
    if v_batch.is_legacy then
      perform public.write_stock_movement(v_item.product_id, v_item.variant_id, 'AJUSTE_ENTRADA',
        v_item.quantity_purchased, current_date, null,
        'Retorno ao saldo sem lote após desfazer associação de legado', v_user);
    end if;
  end loop;
  update public.purchase_batches set status = 'CANCELADO', cancelled_at = now(), closed_at = now()
  where id = p_batch_id;
  perform public.write_audit(v_user, 'purchase.cancelled', 'purchase_batches', p_batch_id, '{}'::jsonb);
end;
$$;

alter table public.purchase_batches enable row level security;
alter table public.batch_items enable row level security;
alter table public.sale_item_batch_allocations enable row level security;
create policy purchase_batches_select on public.purchase_batches for select to authenticated using (true);
create policy batch_items_select on public.batch_items for select to authenticated using (true);
create policy sale_batch_allocations_select on public.sale_item_batch_allocations for select to authenticated using (true);
grant select on public.purchase_batches, public.batch_items, public.sale_item_batch_allocations,
  public.batch_item_balances, public.batch_item_overview, public.batch_overview to authenticated;

revoke all on function public.allocate_sale_item_fifo(uuid, uuid, uuid, integer, date, numeric, numeric, uuid) from public;
revoke all on function public.create_purchase(jsonb) from public;
grant execute on function public.create_purchase(jsonb) to authenticated;
revoke all on function public.cancel_purchase_batch(uuid) from public;
grant execute on function public.cancel_purchase_batch(uuid) to authenticated;
notify pgrst, 'reload schema';
